version: '3'
services:
  backend:
    build: ./backend
    command: go run main.go
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
  frontend:
    build: ./frontend
    command: bash -c "npm install && ng serve --host 0.0.0.0"
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
