version: '3'
services:
  backend:
    build: ./backend
    command: go run main.go
    volumes:
      - .:/app
    ports:
      - 8080:8080
    links:
      - frontend
  frontend:
    image: ./frontend
    build: .
    command: bash -c "npm install && ng serve --host 0.0.0.0"
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "4200:4200"
    links:
      - backend